### ISSUE TITLE
`cargo-build` failed to open git index

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/cargo#11861]
### Problem

`cargo-build` on freshly cloned [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall) failed due to:

```
error: failed to determine package fingerprint for build script for detect-targets v0.1.6 (/Users/nobodyxu/Dev/cargo-binstall/crates/detect-targets)

Caused by:
  failed to determine the most recently modified file in /Users/nobodyxu/Dev/cargo-binstall/crates/detect-targets

Caused by:
  failed to determine list of files in /Users/nobodyxu/Dev/cargo-binstall/crates/detect-targets

Caused by:
  failed to open git index at /Users/nobodyxu/Dev/cargo-binstall/.git/

Caused by:
  invalid data in index - calculated checksum does not match expected; class=Index (10)
```

### Steps

1. `git clone https://github.com/cargo-bins/cargo-binstall`
2. `cd cargo-binstall`
3. `cargo b`

### Version

```text
cargo 1.68.0 (115f34552 2023-02-26)
release: 1.68.0
commit-hash: 115f34552518a2f9b96d740192addbac1271e7e6
commit-date: 2023-02-26
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0 (sys:0.4.59+curl-7.86.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.2.1 [64-bit]
```

**Comment by NobodyXu** [comment]
Somehow this succeeds on [CI](https://github.com/cargo-bins/cargo-binstall/actions/runs/4434391322/jobs/7780425639) but failed on my MacBook.

**Comment by weihanglo** [comment]
Guess it is the same as <https://github.com/rust-lang/cargo/issues/11857>?

**Comment by NobodyXu** [comment]
Yeah, I do enable `feature.manyFiles` but I'm using `git 2.40.0`, which should not have this corrupted index problem.
I will try manually disabling `index.skipHash`.

**Comment by NobodyXu** [comment]
I've manually disabled `index.skipHash` and it indeed works for me!
@weihanglo Thank you!

Also, this also happens if I use `cargo +nightly b -Zgitoxide`

**Comment by weihanglo** [comment]
Good to know that! Thanks.

cc @Byron I am not sure if gitoxide is required to do something. Just FYI.

**Comment by Byron** [comment]
Thanks for letting me know. Indeed, it's firmly a `git2` issue, but the underlying problem might in fact be a corrupted index file. It would be interesting to know what `git` thinks about the index - `git ls-files` in the crates-index clone should come up with something. `git read-tree HEAD` should fix it by recreating it.

**Comment by NobodyXu** [comment]
@Byron `git ls-files` and `git fsck` works just fine on my MacBook.

According to `man git-config`, the corruption is fixed in `git 2.40.0` and it is exactly the version I'm using, so I'm not sure whether this is a corrupted index file.

Using `git read-tree HEAD` also doesn't fix the issue, the only way to fix it is to modify `.gitconfig` to set `index.skipHash` to `false`, rm the repository and `git clone` it again.
