### ISSUE TITLE
Presence of a parent Cargo.toml breaks the resolution of the features for conditional dependencies.

### ISSUE THREAD

**Issue by makemeunsee** [rust-lang/cargo#12821]
### Problem

The resolution of the features for conditional dependencies works for a simple, flat project, e.g.

```toml
[package]
name = "member"

# ...

[target.'cfg(target_family = "wasm")'.dependencies]
tokio = { version = "1", features = ["rt"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
```

but then fails if this project becomes the member of a parent project, e.g.:

```toml
[workspace]
members = ["member"]
```

### Steps

1. clone https://github.com/makemeunsee/cargo_bug/
2. from the repo, run `cargo build` -> all is fine
3. then run `cargo build --target wasm32-unknown-unknown` -> it fails (and it should not)
4. 
    - [option 1] remove `./Cargo.toml`, `cd` to member then `cargo build --target wasm32-unknown-unknown` -> success
    - [option 2] remove lines 11 & 12 of `member/Cargo.toml`, then `cargo build --target wasm32-unknown-unknown` -> success

### Possible Solution(s)

I've tried to work around the issue by declaring workspace dependencies but no, I couldn't get solve the problem.

### Notes

I found already opened issues with similarities, but not a single one which really corresponds, so I filed a new one...

### Version

```text
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
release: 1.70.0
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-unknown-linux-gnu
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by epage** [comment]
While there isn't quite enough information to be sure of the problem, a frequent root cause this matches is fixed by doing
```toml
[workspace]
members = ["member"]
resolver = "2"
```
I think its 1.74 will have a warning to tell you that you should probably do this.

**Comment by weihanglo** [comment]
Just looked into the repro, yep epage is correct. It's the virtual manifest missing `resolver = "2"`.

See [this doc](https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#virtual-workspace) for more information:

> Note that in a virtual manifest the [`resolver = "2"`](https://doc.rust-lang.org/nightly/cargo/reference/resolver.html#resolver-versions) should be specified manually. It is usually deduced from the [`package.edition`](https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-edition-field) field which is absent in virtual manifests and the edition field of a member won’t affect the resolver used by the workspace.

When you `cd` into a member package, since cargo understands it is invoked for a specific package, it then assume `resolver = "2"` for edition 2021 package.

Closing as it is expected and documented. Thank you for the report.

**Comment by makemeunsee** [comment]
Thanks for the explanation! Setting `resolver = "2"` works perfectly, I just wish I had been more aware of it earlier. The warning will be useful indeed.

Just note this is not correct:

> When you cd into a member package, since cargo understands it is invoked for a specific package, it then assume resolver = "2" for edition 2021 package.

That's actually part of the problem I reported, `cd`'ing to the member package did not solve the issue, so I guess `cargo` was nonetheless assuming `resolver = "1"`.

**Comment by weihanglo** [comment]
> That's actually part of the problem I reported, `cd`'ing to the member package did not solve the issue, so I guess `cargo` was nonetheless assuming `resolver = "1"`.

You're absolute correct. It was me also confused by resolver v2 😆.

**Comment by makemeunsee** [comment]
Do you think a PR for all/either of:

* Printing the value of `resolver ` when running `cargo -vv` (I would have spotted the issue then)
* Adding a reference to the `resolver` and its importance in the [Specifying Resolution section](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html) of the docs, and possibly as well under [the Troubleshooting](https://doc.rust-lang.org/nightly/cargo/reference/resolver.html#troubleshooting) too

would be welcome? I understand the maintainers are already very busy and may not be able to focus much on such contribution.

**Comment by epage** [comment]
Keep in mind that we're already going to have a warning about this in 1.74.

For verbose output, I feel like most people with this problem won't understand the implications if we just print it and itd be noise in most cases to an already noisy output.

As for the specifying dependencies, maybe we could cross link to the dependengy resolution section of the book but we have to be careful to fit it in narratively to not detract from the purpose of that section.

**Comment by weihanglo** [comment]
Troubleshooting sounds nice, but only if we could have a concise version of it. It doesnt' seem to be an easy job 😞

**Comment by makemeunsee** [comment]
I would argue that `cargo` saying what resolution algorithm it's using is not noise, but sure, with 1.74 around the corner it's maybe not so much valuable.

And as you put, the doc option is delicate too.

I'll keep my contribution energy for another opportunity :)

Thanks for the feedback!
