### ISSUE TITLE
Prereleases cannot be selected

### ISSUE THREAD

**Issue by nox** [rust-lang/cargo#2337]
I can't currently use expat-sys 2.1.1-really.0 from anywhere.

```
version required: = 2.1.1-really.0
versions found: 2.1.0
```

**Comment by SimonSapin** [comment]
It was fine when I first published that version, I don’t know what changed. @nox, what’s `cargo --version` for this error message?

**Comment by nox** [comment]
```
± cargo --version
cargo 0.7.0-nightly (1af03be 2015-12-08)
```

**Comment by nox** [comment]
I think I am hit by https://github.com/brson/multirust/issues/121 too, so maybe it's fixed in the latest nightly but I can't confirm right now.

**Comment by nox** [comment]
```
± cargo --version
cargo 0.9.0-nightly (6ffd134 2016-01-26)

± cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `expat-sys` found (required by `servo-skia`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^2.1.1-really.0
versions found: 2.1.0
```

**Comment by alexcrichton** [comment]
cc @steveklabnik, perhaps a semver issue?

**Comment by steveklabnik** [comment]
```rust
    // https://docs.npmjs.com/misc/semver#prerelease-tags
    fn pre_tag_is_compatible(&self, ver: &Version) -> bool {
        // If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be
        // allowed to satisfy comparator sets if at least one comparator with the same [major,
        // minor, patch] tuple also has a prerelease tag.
        !ver.is_prerelease() || (self.major == ver.major &&
                                 self.minor == Some(ver.minor) &&
                                 self.patch == Some(ver.patch) &&
                                 !self.pre.is_empty())
    }
```

That said, the `really` version is now yanked, so I don't have an easy way to check that this still happens. I tried to write a test locally, but ran into https://github.com/alexcrichton/git2-rs/issues/100

**Comment by alexcrichton** [comment]
When added to Cargo's test suite, this failed for me:

```rust
test!(use_semver {                                        
    let p = project("foo")                                
        .file("Cargo.toml", r#"                           
            [project]                                     
            name = "ugh"                                  
            version = "0.5.0"                             
            authors = []                                  
                                                          
            [dependencies]                                
            foo = "1.2.3-alpha.0"                         
        "#)                                               
        .file("src/main.rs", "fn main() {}");             
    p.build();                                            
                                                          
    Package::new("foo", "1.2.3-alpha.0").publish();       
                                                          
    assert_that(p.cargo("build"), execs().with_status(0));
});                                                       
```

**Comment by steveklabnik** [comment]
Yes, this is a bug in Semver: https://github.com/steveklabnik/semver/issues/73

I'll see what I can do
