### ISSUE TITLE
Cargo rebuilds workspace member when building root even if workspace member was just built

### ISSUE THREAD

**Issue by jackcmay** [rust-lang/cargo#6337]
**Problem**

Building a workspace root after building a workspace member causes the workspace member to be rebuilt.  Seem to be related to project dependencies and that fact that the member is a cdylib.

The example project below's `README.md` has a number of different to make the problem go away but none of them should be the solution to the problem.

**Steps**
Example project that recreates the issue:
`https://github.com/jackcmay/sandbox_rust_rebuilds/blob/master/README.md`

**Notes**

Output of `cargo version`: cargo 1.30.0 (a1a4ad372 2018-11-02)

**Comment by ehuss** [comment]
This should be fixed in beta (1.31) via #6170.

**Comment by jackcmay** [comment]
We've noticed that locally the build times between stable and beta 1.31 are the same but in docker, we are seeing a noticeable difference in build times. (2 for stable, 13 for beta)

**Comment by ehuss** [comment]
@jackcmay Can you provide a reproduction or more information?  Is it building more stuff in beta, or is it just running more slowly?

**Comment by jackcmay** [comment]
@ehuss I'm not able to recreate the issue outside of our CI environment, sorry.

**Comment by Arnavion** [comment]
For anyone landing here from web search, this issue still happens for crates that have `panic=abort` and are compiled for both cdylib as well as rlib (for other dependencies). It appears to be tracked by https://github.com/rust-lang/cargo/issues/6313

>`panic="abort"` and cdylibs and tests: Create a project with a lib (cdylib crate type), binary, and an integration test, with `panic="abort"` in the profile. When `cargo test` runs, the cdylib is built twice (once with panic=abort for the binary, and once without for the test), with the same filename. Building the lib for the test should probably skip the `cdylib` crate type (assuming rlib is also available), but implementing this is very difficult. See [#6313 (comment)](https://github.com/rust-lang/cargo/issues/6313#issuecomment-480014371).
