### ISSUE TITLE
`error adding symbols: file format not recognized`

### ISSUE THREAD

**Issue by toku-sa-n** [rust-lang/cargo#8239]
**Problem**

The file format of the output binary of `cargo build -Zbuild-std=core,alloc` is not recognized.

**Steps**

1. Clone https://github.com/toku-sa-n/cargo_bug
2. `git checkout with_rlibc`
3. `make`

This causes the error: `ld: target/cargo_settings/debug/librust_bug.a: error adding symbols: file format not recognized`

**Possible Solution(s)**

Sorry, but I have no idea.

**Notes**

Output of `cargo version`:cargo 1.45.0-nightly (cb06cb269 2020-05-08)

`rlibc` is deprecated, but with `compiler_builtins` (which is the replacement of `rlibc`) , `cargo build -Zbuild-std=core,alloc` itself fails with the error: `multiple rlib candidates for compiler_builtins found`. https://github.com/rust-lang/wg-cargo-std-aware/issues/53 seems to be related.

Building without `compiler_builtins` will cause another linker error: `undefined reference to 'memcpy'`.

Related issue: https://github.com/rust-osdev/cargo-xbuild/issues/69

**Comment by lights0123** [comment]
I have this issue on my [custom target](https://github.com/lights0123/ndless-rs/blob/master/cargo-ndless/src/armv5te-nspire-eabi.json) when [specifying `lto = true`](https://github.com/lights0123/example-nspire/blob/ff29e8fc7b72c8833ad6c971806f68d321cefaa4/Cargo.toml#L10):
```
  = note: "nspire-gcc" "-L" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/sysroot/lib/rustlib/armv5te-nspire-eabi/lib" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/armv5te-nspire-eabi/release/deps/async_demo-4f8ee0faccd8ac66.async_demo.42x0nugk-cgu.4.rcgu.o" "-o" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/armv5te-nspire-eabi/release/deps/async_demo-4f8ee0faccd8ac66" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/armv5te-nspire-eabi/release/deps" "-L" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/release/deps" "-L" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/sysroot/lib/rustlib/armv5te-nspire-eabi/lib" "-Wl,--start-group" "-Wl,--end-group" "-Wl,-Bstatic" "/home/benschattinger/Documents/Projects/Calculator/example-nspire/target/sysroot/lib/rustlib/armv5te-nspire-eabi/lib/libcompiler_builtins-3330920514730093.rlib" "-Wl,-Bdynamic" "-Wl,--allow-multiple-definition"
  = note: arm-none-eabi-ld: /home/benschattinger/Documents/Projects/Calculator/example-nspire/target/sysroot/lib/rustlib/armv5te-nspire-eabi/lib/libcompiler_builtins-3330920514730093.rlib: error adding symbols: file format not recognized
          collect2: error: ld returned 1 exit status
```
This occurs both with cargo-xbuild and `-Zbuild-std=core,alloc`.

**Comment by alexcrichton** [comment]
Cargo recently had changes with LTO and optimizing build times by producing object files that are actually LLVM bitcode. I suspect this is a bug where LLVM bitcode is making its way to the linker when it shouldn't.

Would it be possible to minimize this to a small Cargo project perhaps?

**Comment by alexcrichton** [comment]
Ok I got a chance to dig into this a bit. This is definitely `-Zbuild-std`-specific.

The problem here is that Cargo is compiling the crate graph with `-Clinker-plugin-lto`, but crates like `compiler-builtins` and `rlibc` [do not participate in LTO](https://github.com/rust-lang/rust/blob/9e2a6a29ce82e4fc5decad86dab7911a38582438/src/librustc_codegen_ssa/back/link.rs#L720-L726) because they're marked with `#![no_builtins]`.

I think there's a few ways we could fix this:

* Update rustc to ignore `-Clinker-plugin-lto` if the crate is marked with `#![no_builtins]`. I don't think it's basically ever correct for these crates to participate in LTO.
* Update Cargo to learn about `#![no_builtins]` and don't pass these flags.
* Update Cargo with specific knowledge about compiler-builtins and leave rlibc broken.

I'll see if I can whip up a patch to do the first of these.

**Comment by alexcrichton** [comment]
Ok this should be fixed with https://github.com/rust-lang/rust/pull/72325

**Comment by ehuss** [comment]
I'm going to close this as fixed, per rust-lang/rust#72325.

There's still some open questions about how compiler-builtins symbols are working -- whether or not it uses the "mem" feature, particularly for JSON spec targets, and how those symbols are exported.  I still get undefined references from memcpy to various things in libcore even with the `mem` feature.  Tracking those in https://github.com/rust-lang/wg-cargo-std-aware/issues/53.

**Comment by Vurich** [comment]
I'm getting this issue when compiling under aarch64 Arch Linux (I don't know if it happens on other distros because they have too-old a version of ld and it causes some problems with the latest Clang version). I'm compiling C++ code and linking to it from Rust. Disabling LTO in both clang and cargo fixes the issue. Under x86_64 Arch Linux it works.
